Repository Team-Clody/Clody_server, pull requests merged in 2024-09, with the labels that each got.

#176 Feat/#167 : 푸시알림 예약 발송을 구현합니다.
  build.gradle.kts
  clody-app/src/main/java/com/clody/clodyapi/user/controller/UserControllerImpl.java
  clody-batch/build.gradle.kts
  clody-batch/gradle/wrapper/gradle-wrapper.properties
  clody-batch/gradlew
  clody-batch/gradlew.bat
  clody-batch/src/main/java/com/clody/clodybatch/ClodyBatchApplication.java
  clody-batch/src/main/java/com/clody/clodybatch/config/BatchAutoConfiguration.java
  clody-batch/src/main/java/com/clody/clodybatch/config/BatchConfig.java
  clody-batch/src/main/java/com/clody/clodybatch/config/Inspector.java
  clody-batch/src/main/java/com/clody/clodybatch/config/ReplyJobConfig.java
  clody-batch/src/main/java/com/clody/clodybatch/config/ReplyNotificationJobParameter.java
  clody-batch/src/main/java/com/clody/clodybatch/config/ReplyNotificationStepConfig.java
  clody-batch/src/main/java/com/clody/clodybatch/service/ReplyNotificationService.java
  clody-batch/src/main/java/com/clody/clodybatch/service/ReplyNotificationTasklet.java
  clody-batch/src/main/java/com/clody/clodybatch/service/ReplyScheduleService.java
  clody-batch/src/test/java/com/clody/clodybatch/reply/ReplyAlarmServiceTest.java
  clody-batch/src/test/java/com/clody/clodybatch/reply/ReplyNotificationTaskletTest.java
  clody-batch/src/test/java/com/clody/clodybatch/reply/ReplyScheduledServiceTest.java
  clody-domain/src/main/java/com/clody/domain/alarm/Alarm.java
  clody-domain/src/main/java/com/clody/domain/alarm/dto/ScheduleAlarmInfo.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/AlarmPublisher.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/AlarmPublisherImpl.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/ReplyCompletionHandler.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/UploadDiaryEvent.java
  clody-domain/src/main/java/com/clody/domain/alarm/service/AlarmScheduler.java
  clody-domain/src/main/java/com/clody/domain/alarm/strategy/DeletedAlarmDelayStrategy.java
  clody-domain/src/main/java/com/clody/domain/alarm/strategy/DynamicAlarmDelayStrategy.java
  clody-domain/src/main/java/com/clody/domain/alarm/strategy/FirstAlarmDelayStrategy.java
  clody-domain/src/main/java/com/clody/domain/alarm/strategy/RelativeTime.java
  clody-domain/src/main/java/com/clody/domain/alarm/strategy/ScheduleAlarmTimeFactory.java
  clody-domain/src/main/java/com/clody/domain/alarm/strategy/ScheduleTimeDelayStrategyFactory.java
  clody-domain/src/main/java/com/clody/domain/alarm/strategy/ScheduleTimeStrategy.java
  clody-domain/src/main/java/com/clody/domain/alarm/strategy/StaticAlarmDelayStrategy.java
  clody-domain/src/main/java/com/clody/domain/reply/dto/CreationMessage.java
  clody-domain/src/main/java/com/clody/domain/reply/service/processors/ReplyCompletionProcessor.java
  clody-domain/src/main/java/com/clody/meta/Schedule.java
  clody-domain/src/main/java/com/clody/meta/repository/ScheduleMetaRepository.java
  clody-infra/build.gradle.kts
  clody-infra/src/main/java/com/clody/infra/config/AutoWiringSpringBeanJobFactory.java
  clody-infra/src/main/java/com/clody/infra/config/TransactionManagerConfig.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/AlarmQuartzScheduler.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/AlarmRepositoryAdapter.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/JpaAlarmRepository.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/ReplayNotificationJob.java
  clody-infra/src/main/java/com/clody/infra/models/user/strategy/GoogleAuthStrategy.java
Labels: Feature

#181 Hotfix: 카카오 로그인 오류 해결
  clody-infra/src/main/java/com/clody/infra/models/user/strategy/KakaoAuthStrategy.java
Labels: HotFix

#190 Feat/#189: 10분단위 스케줄링 구현
  clody-batch/src/test/java/com/clody/clodybatch/reply/ReplyScheduledServiceTest.java
  clody-domain/src/main/java/com/clody/meta/Schedule.java
  clody-infra/src/main/java/com/clody/infra/config/SchedulingConfig.java
  clody-infra/src/main/java/com/clody/infra/config/TimeConfig.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/DiaryNotifyService.java
  clody-infra/src/test/java/com/clody/infrastructure/alarm/fcm/DiarySchedulingTest.java
Labels: Feature

#191 Fix : 첫 요청 응답시간 수정
  clody-support/src/main/java/com/clody/support/constants/MessageProcessConstants.java
Labels: Fix

#195 Fix : 답변 조회 상태값 반환 로직 수정
  clody-domain/src/main/java/com/clody/domain/reply/dto/ReplyResponse.java
  clody-domain/src/main/java/com/clody/domain/reply/service/ReplyQueryService.java
  clody-domain/src/test/java/com/clody/domain/reply/ReplyQueryServiceTest.java
  clody-support/src/main/java/com/clody/support/constants/MessageProcessConstants.java
  clody-support/src/main/java/com/clody/support/security/util/JwtUtil.java
Labels: Fix

#198 Fix : 처리 실패시 예외 발생
  clody-domain/src/main/java/com/clody/domain/reply/service/processors/RodyMessageProcessor.java
Labels: Fix
