Repository Team-Clody/Clody_server, pull requests merged in 2024-07, with the labels that each got.

#25 Feat: Entity를 생성합니다.
  src/main/java/com/donkeys_today/server/domain/alarm/Alarm.java
  src/main/java/com/donkeys_today/server/domain/alarm/AlarmRepository.java
  src/main/java/com/donkeys_today/server/domain/diary/Diary.java
  src/main/java/com/donkeys_today/server/domain/diary/DiaryRepository.java
  src/main/java/com/donkeys_today/server/domain/reply/Reply.java
  src/main/java/com/donkeys_today/server/domain/reply/ReplyRepository.java
  src/main/java/com/donkeys_today/server/domain/user/ProviderType.java
  src/main/java/com/donkeys_today/server/domain/user/RoleType.java
  src/main/java/com/donkeys_today/server/domain/user/User.java
Labels: Feature

#26 Feat : 카카오 소셜 로그인을 구현합니다.
  src/main/java/com/donkeys_today/server/application/auth/JwtProviderImpl.java
  src/main/java/com/donkeys_today/server/application/user/UserAuthenticator.java
  src/main/java/com/donkeys_today/server/application/user/UserCreater.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/application/user/dto/request/UserSignUpRequest.java
  src/main/java/com/donkeys_today/server/application/user/dto/response/UserResponse.java
  src/main/java/com/donkeys_today/server/application/user/dto/response/UserSignUpResponse.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/SocialRegisterSterategy.java
  src/main/java/com/donkeys_today/server/common/constants/Constants.java
  src/main/java/com/donkeys_today/server/domain/user/Platform.java
  src/main/java/com/donkeys_today/server/domain/user/SocialLoginPlatform.java
  src/main/java/com/donkeys_today/server/domain/user/User.java
  src/main/java/com/donkeys_today/server/domain/user/UserRepository.java
  src/main/java/com/donkeys_today/server/infrastructure/redis/RedisRefreshTokenRepository.java
  src/main/java/com/donkeys_today/server/presentation/user/RedirectController.java
  src/main/java/com/donkeys_today/server/presentation/user/UserController.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/SocialLoginRequest.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/UserSignInRequest.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/UserSignUpRequest.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/response/UserSignInResponse.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/response/UserSignUpResponse.java
  src/main/java/com/donkeys_today/server/support/auth/config/SecurityConfig.java
  src/main/java/com/donkeys_today/server/support/dto/ApiResponse.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/exception/InternalServerException.java
  src/main/java/com/donkeys_today/server/support/exception/UnauthorizedException.java
  src/main/java/com/donkeys_today/server/support/feign/config/FeignConfig.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/KakaoTokenResponse.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/KakaoUserInfoResponse.java
  src/main/java/com/donkeys_today/server/support/feign/kakao/KakaoAuthClient.java
  src/main/java/com/donkeys_today/server/support/feign/kakao/KakaoFeignConfiguration.java
  src/main/java/com/donkeys_today/server/support/feign/kakao/KakaoUserInfoClient.java
  src/main/java/com/donkeys_today/server/support/jwt/JWTConstants.java
  src/main/java/com/donkeys_today/server/support/jwt/JWTUtil.java
  src/main/java/com/donkeys_today/server/support/jwt/JwtProvider.java
  src/main/java/com/donkeys_today/server/support/jwt/JwtTokenProvider.java
  src/main/java/com/donkeys_today/server/support/jwt/RefreshTokenRepository.java
  src/main/java/com/donkeys_today/server/support/jwt/Token.java
  src/main/java/com/donkeys_today/server/support/security/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/donkeys_today/server/support/security/auth/UserAuthentication.java
  src/main/java/com/donkeys_today/server/support/security/config/CorsMvcConfig.java
  src/main/java/com/donkeys_today/server/support/security/config/SecurityConfig.java
  src/main/java/com/donkeys_today/server/support/security/config/WhiteListConstants.java
  src/main/java/com/donkeys_today/server/support/security/filter/ExceptionHandlingFilter.java
  src/main/java/com/donkeys_today/server/support/security/filter/JwtAuthenticationFilter.java
  src/test/java/com/donkeys_today/server/application/jwt/JwtProviderTest.java
Labels: Feature, Test

#27 Feat : Enum 관련 오류를 해결합니다.
  .gitignore
  src/main/java/com/donkeys_today/server/domain/user/Platform.java
  src/main/java/com/donkeys_today/server/domain/user/ProviderType.java
  src/main/java/com/donkeys_today/server/domain/user/RoleType.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/feign/kakao/KakaoUserInfoClient.java
  src/main/java/com/donkeys_today/server/support/jwt/JWTConstants.java
  src/main/java/com/donkeys_today/server/support/jwt/JwtValidationType.java
Labels: Bug

#29 Feat : 배포 오류 수정
  .github/workflows/cicd-pipeline.yml
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
Labels: Bug

#33 Feat/#32 API 문서 작성 방식을 변경합니다.
  .gitignore
  build.gradle
  src/main/java/com/donkeys_today/server/presentation/api/UserController.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/UserSignInRequest.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/UserSignUpRequest.java
  src/main/java/com/donkeys_today/server/support/security/config/WhiteListConstants.java
  src/main/java/com/donkeys_today/server/support/swagger/config/SwaggerConfig.java
  src/test/java/com/donkeys_today/server/docs/RestDocsSupport.java
  src/test/java/com/donkeys_today/server/docs/user/UserControllerDocsTest.java
Labels: Documentation, Feature

#34 Feat : Swagger Https환경을 설정합니다.
  src/main/java/com/donkeys_today/server/support/swagger/config/SwaggerConfig.java
Labels: Infrastructure

#37 Feat: 소셜 로그인 구현
  build.gradle
  src/main/java/com/donkeys_today/server/application/auth/JwtProviderImpl.java
  src/main/java/com/donkeys_today/server/application/user/UserAuthenticator.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/AppleAuthStrategy.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/GoogleAuthStrategy.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/SocialRegisterSterategy.java
  src/main/java/com/donkeys_today/server/domain/user/Platform.java
  src/main/java/com/donkeys_today/server/domain/user/User.java
  src/main/java/com/donkeys_today/server/domain/user/UserRepository.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/SocialLoginRequest.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/UserSignInRequest.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/UserSignUpRequest.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/feign/apple/AppleAuthClient.java
  src/main/java/com/donkeys_today/server/support/feign/apple/AppleFeignConfiguration.java
  src/main/java/com/donkeys_today/server/support/feign/apple/AppleIdTokenPayload.java
  src/main/java/com/donkeys_today/server/support/feign/apple/AppleIdentityTokenParser.java
  src/main/java/com/donkeys_today/server/support/feign/apple/AppleLoginUtil.java
  src/main/java/com/donkeys_today/server/support/feign/apple/ApplePublicKeyGenerator.java
  src/main/java/com/donkeys_today/server/support/feign/apple/ApplePublicKeysClient.java
  src/main/java/com/donkeys_today/server/support/feign/apple/TokenDecoder.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/KakaoUserInfoResponse.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/apple/ApplePublicKey.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/apple/ApplePublicKeyResponse.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/apple/ApplePublicKeys.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/apple/AppleTokenResponse.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/google/GoogleTokenResponse.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/google/GoogleUserInfoResponse.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/kakao/KakaoTokenResponse.java
  src/main/java/com/donkeys_today/server/support/feign/dto/response/kakao/KakaoUserInfoResponse.java
  src/main/java/com/donkeys_today/server/support/feign/google/GoogleAuthClient.java
  src/main/java/com/donkeys_today/server/support/feign/google/GoogleFeignConfiguration.java
  src/main/java/com/donkeys_today/server/support/feign/google/GoogleUserInfoClient.java
  src/main/java/com/donkeys_today/server/support/feign/kakao/KakaoAuthClient.java
  src/main/java/com/donkeys_today/server/support/feign/kakao/KakaoUserInfoClient.java
  src/main/java/com/donkeys_today/server/support/jwt/JwtConstants.java
Labels: Feature

#42 Feat: Access 토큰 재발급 API 구현
  src/main/java/com/donkeys_today/server/application/auth/JwtProviderImpl.java
  src/main/java/com/donkeys_today/server/application/user/UserAuthenticator.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/common/constants/Constants.java
  src/main/java/com/donkeys_today/server/infrastructure/refreshToken/redis/RedisRefreshTokenRepository.java
  src/main/java/com/donkeys_today/server/presentation/api/UserController.java
  src/main/java/com/donkeys_today/server/presentation/auth/dto/response/TokenReissueResponse.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
  src/main/java/com/donkeys_today/server/support/jwt/JwtProvider.java
  src/main/java/com/donkeys_today/server/support/jwt/RefreshTokenRepository.java
Labels: Feature

#49 Feat : 일기 작성 기능을 구현합니다.
  src/main/java/com/donkeys_today/server/application/alarm/AlarmService.java
  src/main/java/com/donkeys_today/server/application/alarm/listener/AlarmEventListener.java
  src/main/java/com/donkeys_today/server/application/user/UserAuthenticator.java
  src/main/java/com/donkeys_today/server/domain/alarm/AlarmRepository.java
  src/main/java/com/donkeys_today/server/infrastructure/alarm/AlarmJpaRepository.java
  src/main/java/com/donkeys_today/server/infrastructure/alarm/AlarmRepository.java
  src/main/java/com/donkeys_today/server/infrastructure/reply/ReplyRepository.java
  src/main/java/com/donkeys_today/server/presentation/Diary/DiaryControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/Diary/dto/response/DiaryFullInfo.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
Labels: Feature

#51 Fix : 병합 충돌을 해결합니다.
  src/main/java/com/donkeys_today/server/presentation/Diary/dto/response/DiaryResponse.java
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryController.java
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryCalenderResponse.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryContent.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryCreatedResponse.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryFullInfo.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryListResponse.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiarySimpleInfo.java
Labels: Refactor, Infrastructure

#53 Fix : 경로명을 수정합니다.
  .github/workflows/cicd-pipeline.yml
Labels: Bug, Infrastructure

#55 Fix : Github Actions 파이프라인을 수정합니다.
  .github/workflows/cicd-pipeline.yml
Labels: Bug, Infrastructure

#56 Fix : Github acitons 오류를 해결합니다.
  .github/workflows/cicd-pipeline.yml
Labels: Bug, Infrastructure

#57 Fix/#50
  .github/workflows/cicd-pipeline.yml
Labels: Bug, Infrastructure

#58 Fix : 파이프라인 스크립트 & Config 수정
  src/main/java/com/donkeys_today/server/external/fcm/FcmConfig.java
  src/main/java/com/donkeys_today/server/presentation/api/DiaryController.java
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryController.java
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
Labels: Bug, Documentation, Infrastructure

#63 Feat: 프로필 조회 API 구현
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/presentation/api/UserController.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/response/UserInfoResponse.java
Labels: Feature

#65 Feat: 닉네임 변경 API 구현
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/application/user/UserUpdater.java
  src/main/java/com/donkeys_today/server/domain/user/User.java
  src/main/java/com/donkeys_today/server/presentation/api/UserController.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/requset/UserNamePatchRequest.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/response/UserNamePatchResponse.java
Labels: Feature

#67 Feat : 답변 조회 기능 구현
  src/main/java/com/donkeys_today/server/application/reply/ReplyRetriever.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyUpdater.java
  src/main/java/com/donkeys_today/server/application/reply/listener/RedisReplyMessageListener.java
  src/main/java/com/donkeys_today/server/application/reply/listener/dto/DiaryListenedMessage.java
  src/main/java/com/donkeys_today/server/domain/reply/Reply.java
  src/main/java/com/donkeys_today/server/infrastructure/reply/ReplyRepository.java
  src/main/java/com/donkeys_today/server/presentation/api/ReplyController.java
  src/main/java/com/donkeys_today/server/presentation/reply/ReplyControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/reply/dto/response/ReplyResponse.java
  src/main/java/com/donkeys_today/server/support/config/RedisConfig.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
Labels: Feature

#68 Feat: 일기 작성 시간 조회 API 구현
  src/main/java/com/donkeys_today/server/application/diary/DiaryPolicy.java
  src/main/java/com/donkeys_today/server/application/diary/DiaryRetriever.java
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/presentation/api/DiaryController.java
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/response/DiaryCreatedTimeGetResponse.java
Labels: Feature

#71 Fix: access token 을 이용한 로그인 방식으로 수정
  src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java
Labels: Bug

#72 Refactor: 일기 작성 시간 조회 API 리팩토링
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/application/user/UserCreator.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
Labels: Refactor

#77 Refactor: 일기 조회 기능 리팩터링
  src/main/java/com/donkeys_today/server/application/diary/DiaryReplyUtil.java
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyRetriever.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
  src/main/java/com/donkeys_today/server/presentation/api/DiaryController.java
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryCalenderGetResponse.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryListGetResponse.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryListResponse.java
Labels: Feature, Refactor

#79 Bug: 충돌 해결
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyRetriever.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
  src/main/java/com/donkeys_today/server/presentation/api/DiaryController.java
Labels: Bug, Confilct

#80 Fix : API 문서 최신화를 진행합니다.
  src/main/java/com/donkeys_today/server/application/reply/ReplyRetriever.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
  src/main/java/com/donkeys_today/server/presentation/api/DiaryController.java
  src/main/java/com/donkeys_today/server/presentation/api/ReplyController.java
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/reply/ReplyControllerImpl.java
Labels: Documentation

#85 Feat: 데모데이용 회원탈퇴 기능 구현
  src/main/java/com/donkeys_today/server/application/user/UserRemover.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/domain/alarm/Alarm.java
  src/main/java/com/donkeys_today/server/domain/diary/Diary.java
  src/main/java/com/donkeys_today/server/domain/reply/Reply.java
  src/main/java/com/donkeys_today/server/presentation/api/UserController.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/user/dto/response/UserDeleteResponse.java
Labels: Feature

#87 Feat : 일기 작성시 답변 타입을 반환하도록 추가합니다.
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyCreator.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
  src/main/java/com/donkeys_today/server/domain/reply/Reply.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryCreatedResponse.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/ReplyType.java
  src/main/java/com/donkeys_today/server/support/config/ReplyProperty.java
  src/main/java/com/donkeys_today/server/support/config/YamlPropertySourceFactory.java
Labels: Feature

#91 Feat : 일기 작성시 요청 날짜에 생성되도록 구현
  src/main/java/com/donkeys_today/server/application/diary/DiaryCreator.java
  src/main/java/com/donkeys_today/server/application/diary/DiaryPolicy.java
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
  src/main/java/com/donkeys_today/server/domain/diary/Diary.java
  src/main/java/com/donkeys_today/server/presentation/reply/dto/response/ReplyResponse.java
Labels: Feature

#92 Docs: 중복 회원가입 예외 처리
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
  src/main/java/com/donkeys_today/server/support/exception/auth/SignUpException.java
Labels: Docs

#94 Docs: SignInException 생성
  src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java
  src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
  src/main/java/com/donkeys_today/server/support/exception/auth/SignInException.java
Labels: Docs

#97 Feat : 답변 반환시, 월 / 일을 함께 반환하도록 변경
  src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
  src/main/java/com/donkeys_today/server/presentation/reply/dto/response/ReplyResponse.java
Labels: Feature, Fix

#99 Docs : 답변 중복 키 예외처리를 구현합니다.
  src/main/java/com/donkeys_today/server/application/diary/DiaryRetriever.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyRetriever.java
  src/main/java/com/donkeys_today/server/application/user/UserAuthenticator.java
  src/main/java/com/donkeys_today/server/application/user/UserRetriever.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/AppleAuthStrategy.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/SocialRegisterSterategy.java
  src/main/java/com/donkeys_today/server/infrastructure/reply/ReplyRepository.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
  src/main/java/com/donkeys_today/server/support/exception/reply/ReplyException.java
Labels: Docs

#100 Fix: security white list 수정
  src/main/java/com/donkeys_today/server/application/auth/JwtProviderImpl.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java
  src/main/java/com/donkeys_today/server/presentation/api/UserController.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/jwt/JwtProvider.java
  src/main/java/com/donkeys_today/server/support/security/config/WhiteListConstants.java
  src/main/java/com/donkeys_today/server/support/security/filter/JwtAuthenticationFilter.java
Labels: Fix

#101 Fix : 일기 조회 로직을 수정합니다.
  src/main/java/com/donkeys_today/server/application/diary/DiaryRetriever.java
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
Labels: Fix

#104 Fix: 일기 삭제 및 조회 로직 수정
  src/main/java/com/donkeys_today/server/application/diary/DiaryPolicy.java
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
Labels: Fix

#108 Refactor: auth 기능을 authController 로 분리
  src/main/java/com/donkeys_today/server/application/user/UserAuthenticator.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/AppleAuthStrategy.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/GoogleAuthStrategy.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java
  src/main/java/com/donkeys_today/server/application/user/sterategy/SocialRegisterSterategy.java
  src/main/java/com/donkeys_today/server/presentation/api/AuthController.java
  src/main/java/com/donkeys_today/server/presentation/api/UserController.java
  src/main/java/com/donkeys_today/server/presentation/auth/AuthControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/auth/dto/request/UserSignInRequest.java
  src/main/java/com/donkeys_today/server/presentation/auth/dto/request/UserSignUpRequest.java
  src/main/java/com/donkeys_today/server/presentation/auth/dto/response/UserSignInResponse.java
  src/main/java/com/donkeys_today/server/presentation/auth/dto/response/UserSignUpResponse.java
  src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
Labels: Refactor

#110 Fix: 사소한 수정
  src/main/java/com/donkeys_today/server/presentation/auth/AuthControllerImpl.java
Labels: Fix

#112 Refactor: cors 보안 삭제
  src/main/java/com/donkeys_today/server/support/security/config/SecurityConfig.java
Labels: Refactor

#113 Docs : 날짜 검증 예외처리를 진행합니다.
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
  src/main/java/com/donkeys_today/server/presentation/reply/ReplyControllerImpl.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
  src/main/java/com/donkeys_today/server/support/exception/InvalidDateFormatException.java
  src/main/java/com/donkeys_today/server/support/util/DateTimeValidator.java
Labels: Docs

#116 Fix : 일기 삭제 반환값 변경
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
Labels: Fix

#117 Feat : 모니터링 서버 종속성을 추가합니다.
  build.gradle
Labels: Infrastructure

#119 Fix: 일기 시간조회 오류 수정
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
Labels: Fix

#124 Fix : 정적 답변 생성 로직을 수정합니다.
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/domain/reply/Reply.java
  src/main/java/com/donkeys_today/server/support/config/ReplyProperty.java
  src/main/java/com/donkeys_today/server/support/config/YamlPropertySourceFactory.java
Labels: Fix

#126 Fix : 정적 답변 생성 로직 수정
  src/main/java/com/donkeys_today/server/application/reply/ReplyCreator.java
  src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
Labels: Fix
