Repository Team-Clody/Clody_server, pull requests merged in 2024-08, with the labels that each got.

#134 Feat: 일기를 삭제한적이 있다면 응답에 isDeleted추가
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryFullInfo.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryResponse.java
  src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiarySimpleInfo.java
Labels: Feature

#141 Feat: 애플로그인 에러 메세지 수정
  src/main/java/com/donkeys_today/server/application/user/sterategy/AppleAuthStrategy.java
Labels: Feature, Refactor

#142 Feat : 답변 작성시 알림 발송 기능을 구현합니다.
  clody-app/src/main/java/com/clody/clodyapi/reply/service/ReplyInsertionProcessor.java
  clody-domain/src/main/java/com/clody/domain/alarm/Alarm.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/AlarmPublisher.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/AlarmPublisherImpl.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/CompletionEvent.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/InitialAlarmEventHandler.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/ReplyCompletionHandler.java
  clody-domain/src/main/java/com/clody/domain/alarm/repository/AlarmRepository.java
  clody-domain/src/main/java/com/clody/domain/alarm/service/AlarmService.java
  clody-domain/src/main/java/com/clody/domain/alarm/service/NotificationSender.java
  clody-domain/src/main/java/com/clody/domain/reply/service/ReplyService.java
  clody-domain/src/main/java/com/clody/domain/reply/service/RodyProcessor.java
  clody-domain/src/main/java/com/clody/domain/reply/service/processors/AlarmEventConverter.java
  clody-domain/src/main/java/com/clody/domain/reply/service/processors/ReplyCompletionProcessor.java
  clody-domain/src/main/java/com/clody/domain/reply/service/processors/ReplyCreationProcessor.java
  clody-domain/src/main/java/com/clody/domain/reply/service/processors/RodyMessageProcessor.java
  clody-infra/src/main/java/com/clody/infra/external/fcm/FcmService.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/AlarmRepositoryAdapter.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/JpaAlarmRepository.java
  clody-infra/src/main/java/com/clody/infra/models/reply/RodyProcessorImpl.java
  clody-support/src/main/java/com/clody/support/dto/type/ErrorType.java
Labels: Feature, Refactor

#136 Feat: 월단위 캘린더 리스트뷰 조회
  .gradle/8.8/fileHashes/fileHashes.lock
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/DiaryRetrieverService.java
  clody-app/src/main/java/com/clody/clodyapi/diary/usecase/DiaryRetrieverUsecase.java
  clody-app/src/main/java/com/clody/clodyapi/legacy/presentation/api/DiaryController.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/DiaryContent.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/DiaryFullInfo.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/DiaryListGetResponse.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/DiarySimpleInfo.java
  clody-domain/src/main/java/com/clody/domain/diary/service/DiaryCommandService.java
Labels: Feature

#147 Feat : 사용자 알람 설정 조회 및 변경 기능을 구현합니다.
  clody-app/src/main/java/com/clody/clodyapi/alarm/controller/AlarmControllerImpl.java
  clody-app/src/main/java/com/clody/clodyapi/alarm/controller/AlarmSwagger.java
  clody-app/src/main/java/com/clody/clodyapi/alarm/dto/request/AlarmUpdateRequest.java
  clody-app/src/main/java/com/clody/clodyapi/alarm/dto/response/AlarmFullResponse.java
  clody-app/src/main/java/com/clody/clodyapi/alarm/dto/response/AlarmResponse.java
  clody-app/src/main/java/com/clody/clodyapi/alarm/service/AlarmRetrieveService.java
  clody-app/src/main/java/com/clody/clodyapi/alarm/service/AlarmUpdateService.java
  clody-app/src/main/java/com/clody/clodyapi/alarm/usecase/RetrieveAlarmInfoUsecase.java
  clody-app/src/main/java/com/clody/clodyapi/alarm/usecase/UpdateAlarmInfoUsecase.java
  clody-domain/src/main/java/com/clody/domain/alarm/Alarm.java
  clody-domain/src/main/java/com/clody/domain/alarm/dto/AlarmTotalInfo.java
  clody-domain/src/main/java/com/clody/domain/alarm/dto/UpdateAlarmCommand.java
  clody-domain/src/main/java/com/clody/domain/alarm/service/AlarmCommandService.java
  clody-domain/src/main/java/com/clody/domain/alarm/service/AlarmQueryService.java
  clody-domain/src/main/java/com/clody/domain/alarm/service/AlarmService.java
Labels: Feature

#149 Feat : 특정 날짜 일기 조회를 구현합니다.
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryController.java
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/dto/response/DiaryContent.java
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/dto/response/DiaryFullInfo.java
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/dto/response/DiaryResponse.java
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/dto/response/ReplyType.java
  clody-app/src/main/java/com/clody/clodyapi/diary/mapper/DiaryMapper.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/DiaryCreationService.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/DiaryRetrievalService.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/DiaryRetrieverService.java
  clody-app/src/main/java/com/clody/clodyapi/diary/usecase/DiaryQueryUsecase.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/DiaryFullInfo.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/DiarySimpleInfo.java
  clody-domain/src/main/java/com/clody/domain/diary/service/DiaryCommandService.java
  clody-domain/src/main/java/com/clody/domain/diary/service/DiaryQueryService.java
Labels: Feature

#152 Feat: 당일 일기 재작성 시 캘린더뷰 조회 diaryCount 미반영 수정
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
Labels: Feature, Fix

#155 Infra : 배포 이전 테스트 환경을 설정합니다.
  .github/workflows/pr-test.yml
  .gitignore
  clody-domain/src/test/java/com/clody/domain/DomainApplicationTests.java
  clody-infra/src/test/java/com/clody/infrastructure/InfrastructureInfraApplicationTests.java
  clody-support/src/test/java/com/clody/support/SupportApplicationTests.java
Labels: Test, Infrastructure

#157 Fix : 배포 전 테스트 오류 수정
  .github/workflows/pr-test.yml
  Dockerfile
  clody-domain/src/main/java/com/clody/DomainApplication.java
Labels: Fix

#161 Fix: 에러응답 추가
  src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
  src/main/java/com/donkeys_today/server/application/user/UserRemover.java
  src/main/java/com/donkeys_today/server/application/user/UserUpdater.java
  src/main/java/com/donkeys_today/server/support/dto/type/SuccessType.java
  src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
  src/main/java/com/donkeys_today/server/support/exception/auth/UserDeleteException.java
Labels: Feature, Fix

#164 Test : 배포 환경 테스트 관련 유지보수를 진행합니다.
  clody-app/src/main/java/com/clody/clodyapi/diary/service/DiaryRetrieverService.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/UserAuthControllerImpl.java
  clody-app/src/main/java/com/clody/clodyapi/user/service/UserApplicationService.java
  clody-domain/src/main/java/com/clody/domain/diary/service/DiaryCommandService.java
  clody-support/src/main/java/com/clody/support/constants/JwtConstants.java
Labels: Test, Fix

#168 Feat#167 : 회원가입/로그인 시 토큰 갱신을 구현합니다.
  clody-app/src/main/java/com/clody/clodyapi/alarm/service/AlarmUpdateService.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserSignInRequest.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserSignUpRequest.java
  clody-app/src/main/java/com/clody/clodyapi/user/service/UserApplicationService.java
  clody-app/src/test/java/com/clody/clodyapi/user/service/UserApplicationServiceTest.java
  clody-domain/src/main/java/com/clody/domain/alarm/Alarm.java
  clody-domain/src/main/java/com/clody/domain/alarm/service/AlarmCommandService.java
Labels: Feature

#170 Feat/#167 : 지연 알림 전송 배치 모듈을 구현합니다.
  .gitignore
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/dto/response/DiaryCreatedTimeResponse.java
  clody-app/src/main/java/com/clody/clodyapi/diary/mapper/DiaryMapper.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/DiaryRetrievalService.java
  clody-app/src/main/java/com/clody/clodyapi/reply/mapper/ReplyMapper.java
  clody-app/src/test/java/com/clody/clodyapi/alarm/service/AlarmUpdateServiceTest.java
  clody-app/src/test/java/com/clody/clodyapi/user/service/UserApplicationServiceTest.java
  clody-batch/build.gradle.kts
  clody-batch/gradle/wrapper/gradle-wrapper.properties
  clody-batch/gradlew
  clody-batch/gradlew.bat
  clody-batch/settings.gradle.kts
  clody-batch/src/main/java/com/clody/clodybatch/ClodyBatchApplication.java
  clody-batch/src/main/java/com/clody/clodybatch/config/BatchConfig.java
  clody-batch/src/main/java/com/clody/clodybatch/config/DataSourceConfig.java
  clody-batch/src/main/java/com/clody/clodybatch/config/ReplyNotificationConfig.java
  clody-batch/src/main/java/com/clody/clodybatch/config/ReplyNotificationStepConfig.java
  clody-batch/src/main/java/com/clody/clodybatch/service/AlarmNotifyService.java
  clody-batch/src/main/java/com/clody/clodybatch/service/ReplyNotificationTasklet.java
  clody-batch/src/main/java/com/clody/clodybatch/service/ScheduleService.java
  clody-batch/src/test/java/com/clody/clodybatch/ClodyBatchApplicationTests.java
  clody-batch/src/test/java/com/clody/clodybatch/reply/ReplyAlarmServiceTest.java
  clody-batch/src/test/java/com/clody/clodybatch/reply/ReplyNotificationTaskletTest.java
  clody-batch/src/test/java/com/clody/clodybatch/reply/ReplyScheduledServiceTest.java
  clody-domain/src/main/java/com/clody/DomainBasePackage.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/AlarmPublisher.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/AlarmPublisherImpl.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/CompletionEvent.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/ReplyCompletionHandler.java
  clody-domain/src/main/java/com/clody/domain/alarm/event/ScheduleEvent.java
  clody-domain/src/main/java/com/clody/domain/alarm/repository/AlarmRepository.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/response/DiaryCreatedInfo.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/response/DiaryTimeInfo.java
  clody-domain/src/main/java/com/clody/domain/diary/service/DiaryQueryService.java
  clody-domain/src/main/java/com/clody/domain/reply/dto/DequeuedMessage.java
  clody-domain/src/main/java/com/clody/domain/reply/dto/Message.java
  clody-domain/src/main/java/com/clody/domain/reply/event/ReplyCreatedEvent.java
  clody-domain/src/main/java/com/clody/domain/reply/event/ReplyEventListener.java
  clody-domain/src/main/java/com/clody/domain/reply/service/ReplyService.java
  clody-domain/src/main/java/com/clody/domain/reply/service/processors/AlarmEventConverter.java
  clody-domain/src/main/java/com/clody/domain/reply/service/processors/ReplyCompletionProcessor.java
  clody-domain/src/main/java/com/clody/meta/Schedule.java
  clody-domain/src/main/java/com/clody/meta/repository/ScheduleMetaRepository.java
  clody-infra/src/main/java/com/clody/infra/config/DataSourceConfig.java
  clody-infra/src/main/java/com/clody/infra/config/DomainDatabaseConfig.java
  clody-infra/src/main/java/com/clody/infra/config/JpaConfig.java
  clody-infra/src/main/java/com/clody/infra/config/MetaDatabaseConfig.java
  clody-infra/src/main/java/com/clody/infra/config/TransactionManagerConfig.java
  clody-infra/src/main/java/com/clody/infra/meta/JpaScheduleMetaRepository.java
  clody-infra/src/main/java/com/clody/infra/meta/ScheduleMetaRepositoryAdapter.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/AlarmRepositoryAdapter.java
  clody-infra/src/main/java/com/clody/infra/models/alarm/JpaAlarmRepository.java
  clody-infra/src/main/java/com/clody/infra/models/reply/RodyProcessorImpl.java
  clody-support/src/main/java/com/clody/support/dto/type/ErrorType.java
  settings.gradle.kts
Labels: Feature, Infrastructure

#173 Feat: 유저 정보 조회 및 수정 삭제 기능 구현
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryController.java
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
  clody-app/src/main/java/com/clody/clodyapi/diary/mapper/DiaryMapper.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/DiaryRetrieverService.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/UserDeletionService.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/UserRetrieverService.java
  clody-app/src/main/java/com/clody/clodyapi/diary/service/UserUpdateService.java
  clody-app/src/main/java/com/clody/clodyapi/diary/usecase/DiaryRetrieverUsecase.java
  clody-app/src/main/java/com/clody/clodyapi/diary/usecase/UserDeletionUsecase.java
  clody-app/src/main/java/com/clody/clodyapi/diary/usecase/UserRetrieverUsecase.java
  clody-app/src/main/java/com/clody/clodyapi/diary/usecase/UserUpdateUsecase.java
  clody-app/src/main/java/com/clody/clodyapi/legacy/presentation/api/DiaryController.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/UserController.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/UserControllerImpl.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserNamePatchRequest.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/response/UserDeleteResponse.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/response/UserInfoGetResponse.java
  clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/response/UserNamePatchResponse.java
  clody-app/src/main/java/com/clody/clodyapi/user/mapper/UserMapper.java
  clody-app/src/main/java/com/clody/clodyapi/user/service/UserApplicationService.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/UserDeletionInfo.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/response/DiaryListGetResponse.java
  clody-domain/src/main/java/com/clody/domain/diary/dto/response/UserGetResponse.java
  clody-domain/src/main/java/com/clody/domain/diary/service/UserCommandService.java
  clody-domain/src/main/java/com/clody/domain/diary/service/UserQueryService.java
  clody-domain/src/main/java/com/clody/domain/user/User.java
  clody-domain/src/main/java/com/clody/domain/user/dto/UserInfo.java
  clody-domain/src/main/java/com/clody/domain/user/service/UserAuthService.java
Labels: Feature, Refactor

#175 Refactor: 캘린더뷰 및 리스트뷰 일기 조회 리팩토링
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryController.java
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
  clody-app/src/main/java/com/clody/clodyapi/diary/controller/dto/request/DiaryRequest.java
  clody-domain/src/main/java/com/clody/domain/diary/service/DiaryQueryService.java
Labels: Refactor
