Repository Team-Clody/Clody_server, pull requests merged in 2024-06, with the labels that each got.

#1 Feat : .gitignore 파일 추가
  .idea/.gitignore
Labels: Feature

#4 Feat : 초기 설정을 진행합니다.
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/donkeys_today/server/DonkeyServerApplication.java
  src/main/java/com/donkeys_today/server/application/user/UserCreater.java
  src/main/java/com/donkeys_today/server/application/user/UserRemover.java
  src/main/java/com/donkeys_today/server/application/user/UserRetriever.java
  src/main/java/com/donkeys_today/server/application/user/UserService.java
  src/main/java/com/donkeys_today/server/application/user/UserUpdater.java
  src/main/java/com/donkeys_today/server/application/user/dto/request/UserSignUpRequest.java
  src/main/java/com/donkeys_today/server/application/user/dto/response/UserResponse.java
  src/main/java/com/donkeys_today/server/application/user/dto/response/UserSignUpResponse.java
  src/main/java/com/donkeys_today/server/domain/user/User.java
  src/main/java/com/donkeys_today/server/domain/user/UserRepository.java
  src/main/java/com/donkeys_today/server/presentation/user/UserController.java
  src/main/java/com/donkeys_today/server/support/auditing/BaseEntity.java
  src/main/java/com/donkeys_today/server/support/auditing/JpaAuditing.java
  src/main/java/com/donkeys_today/server/support/dto/ApiResponse.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/dto/type/SuccessType.java
  src/main/java/com/donkeys_today/server/support/exception/BusinessException.java
  src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
  src/main/java/com/donkeys_today/server/support/exception/NotFoundException.java
  src/test/java/com/donkeys_today/server/DonkeyServerApplicationTests.java
  src/test/java/com/donkeys_today/server/docs/RestDocsSupport.java
  src/test/java/com/donkeys_today/server/docs/user/UserControllerDocsTest.java
  src/test/java/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/java/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: Feature

#5 Feat : 테스트 의존성을 추가합니다.
  build.gradle
  src/main/java/com/donkeys_today/server/presentation/user/UserController.java
  src/test/java/com/donkeys_today/server/docs/RestDocsSupport.java
  src/test/java/com/donkeys_today/server/docs/user/UserControllerDocsTest.java
Labels: Test

#8 Feat: Spring Security Chain 을 설정합니다.
  .gitignore
  build.gradle
  src/main/java/com/donkeys_today/server/auth/config/CorsMvcConfig.java
  src/main/java/com/donkeys_today/server/auth/config/SecurityConfig.java
  src/main/java/com/donkeys_today/server/auth/config/WhiteListConstants.java
Labels: Feature

#9 Refactor : 불필요한 주석을 제거합니다.
  .gitignore
  src/test/java/com/donkeys_today/server/docs/user/UserControllerDocsTest.java
Labels: Refactor

#11 Feat: JwtTokenProvider 구현
  build.gradle
  src/main/java/com/donkeys_today/server/support/auth/config/CorsMvcConfig.java
  src/main/java/com/donkeys_today/server/support/auth/config/SecurityConfig.java
  src/main/java/com/donkeys_today/server/support/auth/config/WhiteListConstants.java
  src/main/java/com/donkeys_today/server/support/config/RedisConfig.java
  src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
  src/main/java/com/donkeys_today/server/support/exception/InternalServerException.java
  src/main/java/com/donkeys_today/server/support/exception/UnauthorizedException.java
  src/main/java/com/donkeys_today/server/support/jwt/JWTConstants.java
  src/main/java/com/donkeys_today/server/support/jwt/JWTUtil.java
  src/main/java/com/donkeys_today/server/support/jwt/JwtTokenProvider.java
  src/main/java/com/donkeys_today/server/support/jwt/JwtValidationType.java
  src/test/java/com/donkeys_today/server/docs/JwtTokenProviderTest.java
  src/test/java/com/donkeys_today/server/docs/JwtUtilsTest.java
  src/test/java/com/donkeys_today/server/docs/user/UserControllerDocsTest.java
Labels: Feature

#14 Feat : docker-compose 를 이용한 무중단 배포 구현
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: Feature

#18 Fix : Redis Container 볼륨 매핑 명시
  docker-compose.yml
Labels: Bug, Infrastructure

#19 Fix : Volume 오탈자를 수정합니다.
  .gitignore
  docker-compose.yml
  src/test/java/com/donkeys_today/server/docs/JwtUtilsTest.java
Labels: Bug, Infrastructure

#22 Fix : DockerFIle CMD 오탈자 수정
  Dockerfile
Labels: Bug, Infrastructure
